export type ModuleStatus =
  | "available"
  | "preparing"
  | "runner_scaffold"
  | "check_mode"
  | "disabled";

export type CommerceModule = {
  id: string;
  title: string;
  navigationLabel?: string;
  description: string;
  status: ModuleStatus;
  route: string | null;
  category: string;
  inputType: string;
  outputType: string;
  historySupport: boolean;
  externalProject: boolean;
  note: string | null;
  helperNote?: string;
  actionLabel?: string;
  safetyBadge?: string;
};

export const moduleRegistry: readonly CommerceModule[] = [
  {
    id: "china-order-cost",
    title: "중국 발주·입고 관리",
    navigationLabel: "중국 발주·입고 관리",
    description:
      "기존 중국 주문 엑셀을 불러와 옵션별 원가를 계산하고, 발주차시 저장부터 입고·누락 확정까지 처리합니다.",
    status: "available",
    route: "/china-order-manager",
    category: "발주·입고 관리",
    inputType: "기존 중국 주문 엑셀, 부대비용, 입고수량",
    outputType: "발주차시, 옵션별 확정원가, 정상입고·불량·누락 기록",
    historySupport: true,
    externalProject: true,
    note: "독립 발주·입고 앱을 엽니다. 상품마스터·실재고·샵플링 재고는 아직 연결하지 않습니다.",
    helperNote: "독립 앱 · 사용 가능",
    actionLabel: "발주·입고 관리 열기",
    safetyBadge: "외부 재고 미변경",
  },
  {
    id: "product-master",
    title: "상품 마스터",
    navigationLabel: "상품 마스터",
    description:
      "상품코드, 모델명, 옵션, 바코드 연결 정보를 한곳에서 관리합니다.",
    status: "available",
    route: "/product-master",
    category: "상품 관리",
    inputType: "상품 및 옵션 데이터",
    outputType: "상품 마스터 기록",
    historySupport: true,
    externalProject: false,
    note: null,
  },
  {
    id: "sourcing-engine",
    title: "1688 주문추천 카드 생성기",
    navigationLabel: "1688 소싱엔진",
    description:
      "실제 수집된 1688 후보 링크 안에서 1순위 주문 후보와 백업 2개를 압축하고, 위험 필터와 테스트 비용 판단을 적용합니다.",
    status: "available",
    route: "/sourcing-engine",
    category: "소싱",
    inputType: "상품명, 경쟁상품 URL, 1688 후보 링크, 목표 판매가, 테스트 예산",
    outputType: "주문 가능/보류/폐기 카드, 1순위 링크, 백업 링크, 대략 원가, 수동 피드백",
    historySupport: true,
    externalProject: false,
    note: "MVP는 완전 자동 소싱이 아니라 수동/반자동 1688 후보 링크를 주문추천 카드로 압축합니다.",
    helperNote: "MVP",
    actionLabel: "소싱 카드 만들기",
  },
  {
    id: "keyword-research",
    title: "키워드 조회",
    navigationLabel: "키워드 조회",
    description:
      "키워드 하나를 입력해 연관 검색어, 월 검색량, 상품 수, 경쟁강도와 우리 엔진의 의미 적합성·기회점수를 비교합니다.",
    status: "available",
    route: "/keyword-research",
    category: "판매 콘텐츠 자동화",
    inputType: "상품 키워드",
    outputType: "연관 키워드, 수요·경쟁·상품 수, 엔진 기회점수, 소싱 후보",
    historySupport: true,
    externalProject: false,
    note: "조회 결과는 시장 판단 보조지표이며 실제 판매량이나 수익성을 보장하지 않습니다.",
    helperNote: "SearchAd + AI 의미 Gate",
    actionLabel: "키워드 조회 열기",
    safetyBadge: "조회·후보저장",
  },
  {
    id: "keyword-opportunity-library",
    title: "키워드 소싱 후보",
    navigationLabel: "키워드 소싱 후보",
    description:
      "상품출시 키워드 엔진 이력에서 경쟁강도가 낮고 품질이 확인된 키워드를 자동으로 모아 다음 소싱 후보로 관리합니다.",
    status: "available",
    route: "/keyword-opportunity-library",
    category: "소싱",
    inputType: "키워드 엔진 경쟁강도 낮음·최적/추천 결과",
    outputType: "중복 제거된 키워드 후보, 검색량, 발견 이력, 소싱 상태·메모",
    historySupport: true,
    externalProject: false,
    note: "현재 후보 원장은 이 브라우저에 저장되며 샵플링이나 외부 마켓을 변경하지 않습니다.",
    helperNote: "키워드 엔진 자동 누적",
    actionLabel: "소싱 후보 보기",
    safetyBadge: "읽기·기록 전용",
  },
  {
    id: "freight-barcode-pdf",
    title: "배대지 바코드 PDF 생성기",
    navigationLabel: "배대지 바코드 PDF 생성기",
    description:
      "배송대행지 신청서 텍스트를 파싱해 작업요청서와 바코드/원산지 라벨 PDF를 생성합니다.",
    status: "available",
    route: "/freight-barcode-request",
    category: "배대지 운영",
    inputType: "배송대행지 신청서 텍스트",
    outputType: "바코드/원산지 라벨 작업요청서 PDF",
    historySupport: true,
    externalProject: false,
    note: "기존 배대지 바코드 작업요청서 흐름을 사용합니다.",
  },
  {
    id: "warehouse-location-sync",
    title: "창고 위치코드 관리",
    navigationLabel: "창고 위치코드 관리",
    description:
      "모델번호와 위치코드 입력 후 샵플링 반영 전 검증합니다.",
    status: "check_mode",
    route: "/warehouse-location-sync",
    category: "창고 운영",
    inputType: "모델번호와 창고 위치코드",
    outputType: "적용계획, 이력, 롤백계획, API 사전검증",
    historySupport: true,
    externalProject: true,
    note: "독립 모듈 commerce-os-warehouse-location-sync를 source of truth로 사용합니다. 실제 샵플링 쓰기/수정 실행은 차단되어 있습니다.",
    helperNote: "점검 모드",
    actionLabel: "점검 화면 열기",
    safetyBadge: "실제 반영 차단",
  },
  {
    id: "warehouse-label-generator",
    title: "창고 라벨 출력기",
    navigationLabel: "창고 라벨 출력기",
    description:
      "창고 위치코드를 CSV 또는 직접 입력으로 받아 50×30mm 롤지용 PDF 라벨을 생성합니다.",
    status: "available",
    route: "/warehouse-label-generator",
    category: "도구",
    inputType: "창고 위치코드 CSV 또는 줄바꿈 텍스트",
    outputType: "50×30mm 창고 위치코드 라벨 PDF",
    historySupport: false,
    externalProject: false,
    note: "Xprinter XP-DT108B 50×30mm 롤지 출력용 MVP입니다.",
  },
  {
    id: "keyword-engine",
    title: "키워드 엔진 실행기",
    navigationLabel: "키워드 엔진 실행기",
    description:
      "샵플링 상품코드(goods_key) 기준으로 외부 키워드 엔진을 실행하고 결과 산출물을 가져옵니다.",
    status: "runner_scaffold",
    route: "/keyword-engine-runner",
    category: "판매 콘텐츠 자동화",
    inputType: "상품 및 판매채널 데이터",
    outputType: "정리된 키워드 묶음",
    historySupport: false,
    externalProject: true,
    note: "외부 keyword-engine-soon 저장소의 GitHub Actions를 통해서만 실행합니다.",
    helperNote: "외부 엔진 실행 가능",
  },
  {
    id: "keyword-review-queue",
    title: "키워드 결과 검토",
    navigationLabel: "키워드 결과 검토",
    description:
      "키워드 엔진 실행 후 가져온 결과물을 검토합니다. 보통은 키워드 엔진 실행기에서 ‘결과 가져오기 및 검토 시작’을 눌러 이동합니다.",
    status: "available",
    route: "/keyword-review-queue",
    category: "keyword",
    inputType: "keyword-engine-soon CSV/Markdown 산출물",
    outputType: "검토된 키워드 승인 데이터",
    historySupport: false,
    externalProject: true,
    note: "승인 행 payload/XML 미리보기만 포함합니다. 실제 Shopling API 실행은 없습니다. 이력 관리는 향후 제공 예정입니다.",
    helperNote: "후속 검토 단계",
    actionLabel: "검토 화면 열기",
  },
  {
    id: "detail-page-studio",
    title: "Commerce OS Detail Page Studio · SaaS 전용",
    navigationLabel: "상세페이지 스튜디오 · SaaS 전용",
    description:
      "상품 이미지와 정보를 입력하면 표준 생성 프로필에 따라 8개 섹션을 만들고, AI 검수·문제 패널 자동보정 후 최종 상세페이지를 제공합니다.",
    status: "available",
    route: "https://commerce-os-detail-page-studio.vercel.app/",
    category: "detail-page",
    inputType:
      "상품 이미지 최대 3장, 상품명, 공급처 정보, 판매 옵션, 선택형 문구 언어",
    outputType:
      "AI 검수된 8개 섹션 상세페이지, 1000×14000 JPG, 대표 1장·부가 4장, 실행·사용량 원장",
    historySupport: false,
    externalProject: true,
    note: "commerce-os-detail-page-studio Production을 최신 운영 기준으로 사용합니다. 기본 Standard 프로필, 다국어 로케일, 실행·사용량 원장이 포함됩니다.",
    helperNote: "최신 운영 버전 · 사용 가능",
    actionLabel: "SaaS 상세페이지 스튜디오 열기",
  },
  {
    id: "detail-page-studio-launch-connector",
    title: "Commerce OS Detail Page Studio · 내부 상품출시진행관리 연결본",
    navigationLabel: "상세페이지 스튜디오 · 내부 연결본",
    description:
      "상품출시진행관리에서 선택한 제품의 중국링크 고정1번을 사용해 상세페이지와 대표·부가 이미지를 만들고, 승인 결과를 해당 상품의 이미지 필드에 자동 연결합니다.",
    status: "available",
    route: "/product-launch-tracker?detailPageDock=1",
    category: "detail-page",
    inputType:
      "상품출시진행관리 선택 행, 중국링크 고정1번, 판매 옵션, 문구 언어",
    outputType:
      "검수 통과 상세페이지 HTML, 대표이미지 URL, 추가이미지 URL, 생성 진행·재생성 이력",
    historySupport: true,
    externalProject: false,
    note: "기존 Commerce OS Detail Page Studio의 생성·AI 검수 규칙을 사용하고 결과 파일을 OPS 영구 저장소에 올린 뒤 상품출시진행관리 필드에 자동 도킹합니다.",
    helperNote: "상품출시진행관리 자동 도킹",
    actionLabel: "내부 연결본 열기",
    safetyBadge: "검수 통과 후 도킹",
  },
  {
    id: "detail-page-ai-review",
    title: "상세페이지 AI 작업 검수",
    navigationLabel: "상세페이지 AI 작업 검수",
    description:
      "신규상품출시관리의 상세페이지 생성 작업을 한눈에 보고, 문제 이미지·검수 사유·1688 원본을 비교해 문제 자산만 이어서 재생성합니다.",
    status: "available",
    route: "/detail-page-ai-review",
    category: "detail-page",
    inputType: "내부 상품출시진행관리 상세페이지 생성·AI 검수 이력",
    outputType: "작업별 이미지 미리보기, 검수 판정, 문제 자산 부분 재생성, 전체 재생성",
    historySupport: true,
    externalProject: false,
    note: "최근 50개 작업과 저장된 체크포인트를 사용합니다. 부분 재생성은 정상 상세 섹션과 승인 이미지를 보존합니다.",
    helperNote: "문제 이미지 확대·부분 재생성",
    actionLabel: "검수·재생성 열기",
    safetyBadge: "정상 자산 보존",
  },
  {
    id: "detail-page-cost-admin",
    title: "상세페이지 생성 원가 관리",
    navigationLabel: "상세페이지 원가 관리",
    description:
      "상품 분석·이미지 생성·AI 검수 호출을 실행 ID별로 집계해 실제 내부 추정 원가를 확인합니다.",
    status: "available",
    route: "/detail-page-costs",
    category: "detail-page",
    inputType: "상세페이지 스튜디오 서버 호출 원장",
    outputType: "누적·일일·실행별 OpenAI 추정 원가",
    historySupport: true,
    externalProject: false,
    note: "승인된 운영자 계정만 접근할 수 있으며 사용자 과금 화면과 분리됩니다.",
    helperNote: "관리자 전용",
    actionLabel: "원가 관리 열기",
    safetyBadge: "내부 정보",
  },
  {
    id: "product-launch-flow",
    title: "상품 출시 플로우",
    navigationLabel: "상품 출시 플로우",
    description:
      "실재고 시트 행번호 기준으로 상품업로드, 가격설정, 상품명/키워드 준비 상태를 연결합니다.",
    status: "runner_scaffold",
    route: "/product-launch-flow",
    category: "채널 자동화",
    inputType: "실재고 시트 행 번호",
    outputType: "상품업로드, 가격설정, 상품명/키워드 준비 상태",
    historySupport: false,
    externalProject: true,
    note: "외부 엔진 실행 결과를 연결하는 MVP 흐름입니다. 마켓전송은 수동으로 진행합니다.",
    helperNote: "MVP 플로우",
    actionLabel: "플로우 열기",
  },
  {
    id: "product-launch-tracker",
    title: "신규 상품 출시 진행관리",
    navigationLabel: "신규 상품 출시 진행관리",
    description:
      "신규 입고 상품의 상세페이지 제작, 가격·키워드, 샵플링 업로드, 마켓 등록, 주문 매핑, 재고 반영 상태를 한곳에서 기록합니다.",
    status: "available",
    route: "/product-launch-tracker",
    category: "상품 출시 관리",
    inputType: "신규 상품 목록, 옵션, 작업 단계 상태",
    outputType: "상품별 진행률, 다음 작업, 담당자, 완료 기록",
    historySupport: true,
    externalProject: true,
    note: "독립 모듈 commerce-os-product-launch-tracker의 검증된 정적 실행본을 OPS Center에서 엽니다. 현재 수정 내용은 브라우저에 자동 저장됩니다.",
    helperNote: "실제 이관 데이터 · 사용 가능",
    actionLabel: "진행관리 열기",
  },
  {
    id: "shopling-product-upload-runner",
    title: "샵플링 상품등록 실행기",
    navigationLabel: "샵플링 상품등록 실행기",
    description:
      "실재고 시트 행 번호를 입력해 외부 상품등록 엔진을 실행합니다.",
    status: "runner_scaffold",
    route: "/shopling-product-upload-runner",
    category: "채널 자동화",
    inputType: "실재고 시트 행 번호 및 채널",
    outputType: "shopling-product-upload-auto 실행 결과",
    historySupport: false,
    externalProject: true,
    note: "로컬 shopling-product-upload-auto 엔진을 서버에서 직접 실행합니다.",
    helperNote: "실제 상품등록 실행",
    actionLabel: "실행기 열기",
  },
  {
    id: "shopling-price-modify-runner",
    title: "샵플링 쇼핑몰별 가격설정 실행기",
    navigationLabel: "샵플링 가격설정 실행기",
    description: "goods_key 기준으로 쇼핑몰별 가격설정을 실행합니다.",
    status: "runner_scaffold",
    route: "/shopling-price-modify-runner",
    category: "채널 자동화",
    inputType: "샵플링 goods_key",
    outputType: "shopling-price-modify-auto result_summary.json",
    historySupport: false,
    externalProject: true,
    note: "OPS Center는 GitHub Actions 실행과 결과 조회만 수행하며 샵플링을 직접 호출하지 않습니다.",
    helperNote: "실제 가격설정 실행",
    actionLabel: "실행기 열기",
  },
  {
    id: "shopling-option-barcode-sync",
    title: "샵플링 옵션 바코드 동기화",
    navigationLabel: "샵플링 옵션 바코드 동기화",
    description:
      "옵션자체관리코드를 같은 옵션 위치의 바코드로 1회 전수 동기화합니다.",
    status: "runner_scaffold",
    route: "/shopling-barcode-sync",
    category: "채널 자동화",
    inputType: "샵플링 전체 상품 옵션",
    outputType: "변경계획, 수정 전 백업, 재조회 검증 결과",
    historySupport: false,
    externalProject: true,
    note: "외부 commerce-os-shopling-barcode-sync-11 GitHub Actions만 실행하며 OPS Center는 샵플링 API를 직접 호출하지 않습니다.",
    helperNote: "1회 전수 동기화",
    actionLabel: "동기화 열기",
    safetyBadge: "10개 테스트 후 전체",
  },
{
    id: "engine-env-setup",
    title: "엔진 환경변수 설정",
    navigationLabel: "엔진 환경변수 설정",
    description:
      "키워드/상세페이지 엔진 실행에 필요한 GitHub Actions Secrets를 점검하고 설정합니다.",
    status: "available",
    route: "/engine-env-setup",
    category: "판매 콘텐츠 자동화",
    inputType: "GitHub Actions Secrets",
    outputType: "외부 엔진 환경변수 설정 상태",
    historySupport: false,
    externalProject: true,
    note: "Secret 값은 OPS CENTER에 저장하지 않습니다.",
    helperNote: "사용 가능",
    actionLabel: "환경변수 설정",
  },
  {
    id: "engine-runner-history",
    title: "엔진 실행 이력",
    navigationLabel: "엔진 실행 이력",
    description:
      "키워드/상세페이지 엔진 실행 요청과 결과물 가져오기 이력을 확인합니다.",
    status: "available",
    route: "/engine-runner-history",
    category: "판매 콘텐츠 자동화",
    inputType: "브라우저 로컬 실행/가져오기 메타데이터",
    outputType: "브라우저 로컬 엔진 실행 이력",
    historySupport: true,
    externalProject: false,
    note: "현재 이력은 이 브라우저에 저장됩니다.",
    helperNote: "사용 가능",
    actionLabel: "이력 보기",
  },
  {
    id: "inventory-price",
    title: "재고 / 가격 관리",
    description: "상품별 재고 수량과 채널별 가격을 관리합니다.",
    status: "preparing",
    route: null,
    category: "재고 운영",
    inputType: "재고 및 채널별 가격 데이터",
    outputType: "재고 및 가격 상태",
    historySupport: false,
    externalProject: false,
    note: "추후 제공",
  },
  {
    id: "shopling-api-automation",
    title: "샵플링 API 자동화",
    description: "검토·승인된 결과만 샵플링 API로 반영하는 실행 모듈입니다.",
    status: "preparing",
    route: null,
    category: "채널 자동화",
    inputType: "판매채널 운영 요청",
    outputType: "자동화 실행 결과",
    historySupport: false,
    externalProject: false,
    note: "추후 제공",
  },
];
