export const MONTHLY_PRICE_POLICY = "MONTHLY_CONFIRMED_COST_OPTION_AWARE_GROUP_RECOVERY_V3";
export const MONTHLY_PRICE_BRIDGE = "commerce-os-monthly-price-v1";
export const MONTHLY_PRICE_EXTENSION_VERSION = "0.5.2";
