import test from 'node:test';
import assert from 'node:assert/strict';
import { sourcingReceiptProofs, reconcileSourcingReceiptArtifacts } from '../src/lib/sourcingReceiptLifecycleCore.ts';
const receiptId='11111111-1111-4111-8111-111111111111';
const intakeId='22222222-2222-4222-8222-222222222222';
const outboxId='33333333-3333-4333-8333-333333333333';
function row() { return { input_snapshot: { sourceLineId:'draft:line', barcode:'BBA8-1', status:'PARTIALLY_RECEIVED', payload:{receiptId,sourcingConfirmed:true} }, result_snapshot:{receiptId,barcode:'BBA8-1',receivedNow:2,sourcing:{intakeId,outboxId,modelNumber:'AAA493',productName:'수납함'},receiptCost:{receiptId,barcode:'BBA8-1',modelNumber:'AAA493',quantity:2,unitCostKrw:2500,receivedAt:'2026-09-20T12:00:00.000Z'}} }; }
function backend() { const calls=[],warehouse=new Set(),launch=new Set();return {calls,warehouse,launch,deps:{ensureWarehouse:async p=>{calls.push('warehouse');warehouse.add(p.intakeId);return{intakeId:p.intakeId,modelNumber:p.modelNumber,skuId:'stable-sku'};},ensureLaunch:async p=>{calls.push('launch');launch.add(p.intakeId);return{itemId:p.intakeId,modelNumber:p.modelNumber};}}}; }
test('committed partial receipt activates exactly one warehouse and launch identity',async()=>{const b=backend();assert.deepEqual(await reconcileSourcingReceiptArtifacts(receiptId,[row()],b.deps),{completed:1});assert.deepEqual(b.calls,['warehouse','launch']);});
test('all receipt proofs are checked before any external mutation',async()=>{const b=backend(),bad=row();bad.result_snapshot.receiptCost.barcode='BBA8-2';await assert.rejects(reconcileSourcingReceiptArtifacts(receiptId,[row(),bad],b.deps),/PROOF_MISMATCH/);assert.deepEqual(b.calls,[]);});
test('warehouse failure does not activate launch; retry reuses immutable identity',async()=>{const b=backend();await assert.rejects(reconcileSourcingReceiptArtifacts(receiptId,[row()],{...b.deps,ensureWarehouse:async()=>{throw Error('NETWORK');}}),/NETWORK/);assert.equal(b.launch.size,0);await reconcileSourcingReceiptArtifacts(receiptId,[row()],b.deps);assert.equal(b.launch.size,1);});
test('lost launch response is recovered without duplicating a product',async()=>{const b=backend();await assert.rejects(reconcileSourcingReceiptArtifacts(receiptId,[row()],{...b.deps,ensureLaunch:async p=>{await b.deps.ensureLaunch(p);throw Error('LOST_RESPONSE');}}),/LOST_RESPONSE/);await reconcileSourcingReceiptArtifacts(receiptId,[row()],b.deps);assert.equal(b.warehouse.size,1);assert.equal(b.launch.size,1);});
test('missing or forged receipt identity never materializes an item',()=>{for(const mutate of [r=>r.result_snapshot.receiptId='wrong',r=>r.result_snapshot.receiptCost.quantity=0,r=>r.result_snapshot.receiptCost.modelNumber='AAA999',r=>r.input_snapshot.status='RESERVED']){const r=row();mutate(r);assert.throws(()=>sourcingReceiptProofs(receiptId,[r]),/PROOF_MISMATCH/);}});
test('duplicate source intake in one batch is rejected rather than received twice',()=>{assert.throws(()=>sourcingReceiptProofs(receiptId,[row(),row()]),/PROOF_DUPLICATE/);});
test('normal replenishment receipts have no sourcing side effects',async()=>{const b=backend();assert.deepEqual(await reconcileSourcingReceiptArtifacts(receiptId,[{input_snapshot:{},result_snapshot:{}}],b.deps),{completed:0});assert.deepEqual(b.calls,[]);});
test('missing sourcing proof cannot silently become an ordinary receipt',()=>{const r=row();delete r.result_snapshot.sourcing;assert.throws(()=>sourcingReceiptProofs(receiptId,[r]),/PROOF_MISSING/);});
test('mismatched warehouse acknowledgement stops launch',async()=>{const b=backend();await assert.rejects(reconcileSourcingReceiptArtifacts(receiptId,[row()],{...b.deps,ensureWarehouse:async()=>({intakeId,modelNumber:'AAA999',skuId:'x'})}),/WAREHOUSE_ACK_MISMATCH/);assert.equal(b.launch.size,0);});
test('receipt retry uses recorded cost, not a later changed draft estimate',()=>{const p=sourcingReceiptProofs(receiptId,[row()])[0];assert.equal(p.unitCostKrw,2500);assert.equal(p.quantity,2);assert.equal(p.receivedAt,'2026-09-20T12:00:00.000Z');});
