"use client";

import { FormEvent, useMemo, useState } from "react";
import { extractUploadGoodsKeyRows, inferProductGroupFromPtnGoodsCd, type ProductLaunchUploadRow, uniqueGoodsKeys } from "@/lib/productLaunchFlow";

const UPLOAD_REQUEST_ID_STORAGE_KEY = "productLaunchFlow.uploadRequestId";
const PRICE_REQUEST_ID_STORAGE_KEY = "productLaunchFlow.priceRequestId";
const LAST_ROW_EXPRESSION_STORAGE_KEY = "productLaunchFlow.lastRowExpression";

type RunResult = { status?: string; message?: string; requestId?: string; githubActionsUrl?: string; commandPreview?: string };
type UploadActionsResult = { status?: string; message?: string; requestId?: string; runUrl?: string; runStatus?: string; runConclusion?: string | null; summary?: unknown };
type PriceActionsResult = { status?: string; message?: string; requestId?: string; runUrl?: string; runStatus?: string; runConclusion?: string | null; summary?: { request_id?: string; goods_key_count?: unknown; estimated_mall_update_count?: unknown; status?: unknown; exit_code?: unknown; ok_count?: unknown; fail_count?: unknown; errors?: ErrorRow[]; policy_override_count?: unknown } };
type ErrorRow = { idx?: string | number; mall?: string; goods_key?: string; code?: string | number; msg?: string };

export function ProductLaunchFlow() {
  const [uploadRunning, setUploadRunning] = useState(false);
  const [uploadFetching, setUploadFetching] = useState(false);
  const [priceRunning, setPriceRunning] = useState(false);
  const [priceFetching, setPriceFetching] = useState(false);
  const [uploadResult, setUploadResult] = useState<RunResult | null>(null);
  const [uploadActionsResult, setUploadActionsResult] = useState<UploadActionsResult | null>(null);
  const [priceResult, setPriceResult] = useState<RunResult | null>(null);
  const [priceActionsResult, setPriceActionsResult] = useState<PriceActionsResult | null>(null);
  const [uploadRequestId, setUploadRequestId] = useState(() => getLocal(UPLOAD_REQUEST_ID_STORAGE_KEY));
  const [priceRequestId, setPriceRequestId] = useState(() => getLocal(PRICE_REQUEST_ID_STORAGE_KEY));
  const [rowExpression, setRowExpression] = useState(() => getLocal(LAST_ROW_EXPRESSION_STORAGE_KEY));
  const goodsKeyRows = useMemo(() => extractUploadGoodsKeyRows(uploadActionsResult?.summary), [uploadActionsResult]);
  const goodsKeys = useMemo(() => uniqueGoodsKeys(goodsKeyRows), [goodsKeyRows]);

  const runUpload = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    if (uploadRunning) return;
    setUploadRunning(true); setUploadResult(null); setUploadActionsResult(null);
    try {
      const formData = new FormData(event.currentTarget);
      const nextRowExpression = formData.get("rowExpression")?.toString() ?? "";
      setRowExpression(nextRowExpression); setLocal(LAST_ROW_EXPRESSION_STORAGE_KEY, nextRowExpression);
      const response = await fetch("/api/shopling-product-upload/run", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ rowExpression: nextRowExpression, channel: "", skip_if_goods_key: formData.get("skip_if_goods_key") === "on", dump: false, sleep: "1.2" }) });
      const data = await response.json(); setUploadResult(data);
      if (typeof data.requestId === "string" && data.requestId) { setUploadRequestId(data.requestId); setLocal(UPLOAD_REQUEST_ID_STORAGE_KEY, data.requestId); }
    } catch (error) { setUploadResult({ status: "error", message: error instanceof Error ? error.message : "상품업로드 실행 요청 중 오류가 발생했습니다." }); }
    finally { setUploadRunning(false); }
  };

  const fetchUploadResult = async () => {
    if (uploadFetching) return; setUploadFetching(true);
    try { const url = uploadRequestId ? `/api/shopling-product-upload/actions-result?request_id=${encodeURIComponent(uploadRequestId)}` : "/api/shopling-product-upload/actions-result"; setUploadActionsResult(await (await fetch(url)).json()); }
    catch (error) { setUploadActionsResult({ status: "error", message: error instanceof Error ? error.message : "상품업로드 결과를 가져오는 중 오류가 발생했습니다." }); }
    finally { setUploadFetching(false); }
  };

  const runPriceModify = async () => {
    if (priceRunning || goodsKeys.length === 0) return; setPriceRunning(true); setPriceResult(null); setPriceActionsResult(null);
    try { const response = await fetch("/api/shopling-price-modify/run", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ goods_key: goodsKeys.join(","), policy_overrides: [] }) }); const data = await response.json(); setPriceResult(data); if (typeof data.requestId === "string" && data.requestId) { setPriceRequestId(data.requestId); setLocal(PRICE_REQUEST_ID_STORAGE_KEY, data.requestId); } }
    catch (error) { setPriceResult({ status: "error", message: error instanceof Error ? error.message : "가격설정 실행 요청 중 오류가 발생했습니다." }); }
    finally { setPriceRunning(false); }
  };

  const fetchPriceResult = async () => {
    if (priceFetching) return; setPriceFetching(true);
    try { const url = priceRequestId ? `/api/shopling-price-modify/actions-result?request_id=${encodeURIComponent(priceRequestId)}` : "/api/shopling-price-modify/actions-result"; setPriceActionsResult(await (await fetch(url)).json()); }
    catch (error) { setPriceActionsResult({ status: "error", message: error instanceof Error ? error.message : "가격설정 결과를 가져오는 중 오류가 발생했습니다." }); }
    finally { setPriceFetching(false); }
  };

  return <div className="space-y-6"><section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-xl font-bold text-slate-950">Step 1. 상품업로드</h2><form onSubmit={runUpload} className="mt-4 grid gap-4"><label className="block text-sm font-semibold text-slate-800">실재고 시트 행 번호<input name="rowExpression" value={rowExpression} onChange={(event) => setRowExpression(event.target.value)} placeholder="예: 950 또는 950-952 또는 950,951" required className="mt-2 w-full rounded-lg border border-slate-300 px-3 py-2 text-sm" /></label><p className="rounded-lg bg-slate-50 p-3 text-sm text-slate-600">채널은 상품 출시 플로우 MVP에서 전체 6채널로 고정됩니다.</p><label className="flex items-center gap-2 text-sm font-medium text-slate-700"><input name="skip_if_goods_key" type="checkbox" defaultChecked className="size-4 rounded border-slate-300" />이미 goods_key 있으면 스킵</label><button type="submit" disabled={uploadRunning} className="w-fit rounded-lg bg-blue-600 px-4 py-2 text-sm font-semibold text-white disabled:bg-slate-400">{uploadRunning ? "실행 요청 중..." : "상품업로드 실행"}</button></form><RunResultPanel result={uploadResult} currentRequestId={uploadRequestId} doneMessage="상품업로드 완료 후 결과 가져오기를 누르세요." /><button type="button" onClick={fetchUploadResult} disabled={uploadFetching} className="mt-5 rounded-lg bg-slate-900 px-4 py-2 text-sm font-semibold text-white disabled:bg-slate-400">{uploadFetching ? "결과 가져오는 중..." : "상품업로드 결과 가져오기"}</button>{uploadActionsResult ? <UploadResultPanel result={uploadActionsResult} rows={goodsKeyRows} /> : null}</section>{goodsKeyRows.length > 0 ? <><section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-xl font-bold text-slate-950">Step 2. 가격설정</h2><dl className="mt-4 grid gap-3 text-sm"><ResultRow label="대상 goods_key 수" value={goodsKeys.length} /><ResultRow label="예상 쇼핑몰 가격설정 대상 수" value={goodsKeys.length * 24} /></dl><p className="mt-3 rounded-lg bg-slate-50 p-3 text-sm text-slate-600">launch flow MVP는 커스텀 가격정책 UI를 제공하지 않고 기본 가격정책만 사용합니다.</p><button type="button" onClick={runPriceModify} disabled={priceRunning || goodsKeys.length === 0} className="mt-5 rounded-lg bg-blue-600 px-4 py-2 text-sm font-semibold text-white disabled:bg-slate-400">{priceRunning ? "실행 요청 중..." : "가격설정 실행"}</button><RunResultPanel result={priceResult} currentRequestId={priceRequestId} /><button type="button" onClick={fetchPriceResult} disabled={priceFetching} className="mt-5 rounded-lg bg-slate-900 px-4 py-2 text-sm font-semibold text-white disabled:bg-slate-400">{priceFetching ? "결과 가져오는 중..." : "가격설정 결과 가져오기"}</button>{priceActionsResult ? <PriceResultPanel result={priceActionsResult} currentRequestId={priceRequestId} /> : null}</section><TitleKeywordSection rows={goodsKeyRows} /><FinalChecklist goodsKeyCount={goodsKeys.length} priceDone={Boolean(priceActionsResult)} /></> : null}</div>;
}

function getLocal(key: string) { if (typeof window === "undefined") return ""; return window.localStorage.getItem(key) ?? ""; }
function setLocal(key: string, value: string) { if (typeof window !== "undefined") window.localStorage.setItem(key, value); }
function RunResultPanel({ result, currentRequestId, doneMessage }: { result: RunResult | null; currentRequestId: string; doneMessage?: string }) { if (!result) return null; return <dl className="mt-4 grid gap-3 text-sm"><ResultRow label="실행 상태" value={result.status === "queued" ? "GitHub Actions 실행 요청됨" : result.status ?? "-"} /><ResultRow label="요청 추적 ID" value={result.requestId ?? currentRequestId ?? "-"} mono />{result.githubActionsUrl ? <LinkRow label="GitHub Actions URL" href={result.githubActionsUrl} /> : null}{result.commandPreview ? <ResultRow label="commandPreview" value={result.commandPreview} mono /> : null}{result.message ? <ResultRow label="message" value={result.message} /> : null}{doneMessage ? <p className="rounded-lg bg-blue-50 p-3 text-sm font-medium text-blue-700">{doneMessage}</p> : null}</dl>; }
function UploadResultPanel({ result, rows }: { result: UploadActionsResult; rows: ProductLaunchUploadRow[] }) { return <div className="mt-6 rounded-xl border border-slate-200 bg-slate-50 p-4"><h3 className="text-base font-bold text-slate-950">상품업로드 결과</h3>{result.message ? <p className="mt-2 text-sm text-slate-700">{result.message}</p> : null}<dl className="mt-4 grid gap-3 text-sm"><ResultRow label="GitHub Actions 실행 상태" value={`${result.runStatus ?? result.status ?? "-"} / ${result.runConclusion ?? "-"}`} /><LinkRow label="GitHub Actions 실행 링크" href={result.runUrl} /><ResultRow label="추출 goods_key 수" value={rows.length} /></dl><GoodsKeyTable rows={rows} /><p className="mt-3 rounded-lg bg-amber-50 p-3 text-sm font-medium text-amber-800">상품그룹은 샵플링 상품그룹 API 수정이 아니라 ptn_goods_cd 앞자리 기준의 Commerce OS 내부 인식값입니다.</p></div>; }
function GoodsKeyTable({ rows }: { rows: ProductLaunchUploadRow[] }) { return <div className="mt-4 overflow-x-auto"><table className="min-w-full border-collapse text-sm"><thead><tr className="bg-white text-left text-slate-700"><th className="border border-slate-200 px-3 py-2">행</th><th className="border border-slate-200 px-3 py-2">상품그룹</th><th className="border border-slate-200 px-3 py-2">채널</th><th className="border border-slate-200 px-3 py-2">code</th><th className="border border-slate-200 px-3 py-2">goods_key</th><th className="border border-slate-200 px-3 py-2">ptn_goods_cd</th></tr></thead><tbody>{rows.length > 0 ? rows.map((row, index) => <tr key={`${row.goods_key}-${index}`} className="bg-white odd:bg-slate-50/60"><td className="border border-slate-200 px-3 py-2">{row.row || "-"}</td><td className="border border-slate-200 px-3 py-2 font-semibold">{inferProductGroupFromPtnGoodsCd(row.ptn_goods_cd)}</td><td className="border border-slate-200 px-3 py-2">{row.channel || "-"}</td><td className="border border-slate-200 px-3 py-2">{row.code || "-"}</td><td className="border border-slate-200 px-3 py-2 font-mono">{row.goods_key}</td><td className="border border-slate-200 px-3 py-2 font-mono">{row.ptn_goods_cd || "-"}</td></tr>) : <tr><td className="border border-slate-200 px-3 py-2 text-slate-500" colSpan={6}>goods_key 결과가 없습니다.</td></tr>}</tbody></table></div>; }
function PriceResultPanel({ result, currentRequestId }: { result: PriceActionsResult; currentRequestId: string }) { const summary = result.summary; const errors = Array.isArray(summary?.errors) ? summary.errors : []; return <div className="mt-6 rounded-xl border border-slate-200 bg-slate-50 p-4"><h3 className="text-base font-bold text-slate-950">가격설정 결과</h3><dl className="mt-4 grid gap-3 text-sm"><ResultRow label="GitHub Actions 실행 상태" value={`${result.runStatus ?? result.status ?? "-"} / ${result.runConclusion ?? "-"}`} /><LinkRow label="GitHub Actions 실행 링크" href={result.runUrl} /><ResultRow label="요청 추적 ID" value={summary?.request_id ?? result.requestId ?? currentRequestId ?? "-"} mono /><ResultRow label="status" value={String(summary?.status ?? "-")} /><ResultRow label="exit_code" value={String(summary?.exit_code ?? "-")} /><ResultRow label="goods_key_count" value={String(summary?.goods_key_count ?? "-")} /><ResultRow label="estimated_mall_update_count" value={String(summary?.estimated_mall_update_count ?? "-")} /><ResultRow label="policy_override_count" value={String(summary?.policy_override_count ?? "-")} /><ResultRow label="성공 수" value={String(summary?.ok_count ?? "-")} /><ResultRow label="실패 수" value={String(summary?.fail_count ?? "-")} /></dl><ErrorsTable errors={errors} /></div>; }
function ErrorsTable({ errors }: { errors: ErrorRow[] }) { return <div className="mt-4 overflow-x-auto"><table className="min-w-full border-collapse text-sm"><thead><tr className="bg-white text-left text-slate-700"><th className="border border-slate-200 px-3 py-2">idx</th><th className="border border-slate-200 px-3 py-2">mall</th><th className="border border-slate-200 px-3 py-2">goods_key</th><th className="border border-slate-200 px-3 py-2">code</th><th className="border border-slate-200 px-3 py-2">msg</th></tr></thead><tbody>{errors.length > 0 ? errors.map((row, index) => <tr key={`${row.idx ?? index}-${row.goods_key ?? ""}`} className="bg-white"><td className="border border-slate-200 px-3 py-2">{row.idx ?? index + 1}</td><td className="border border-slate-200 px-3 py-2">{row.mall ?? "-"}</td><td className="border border-slate-200 px-3 py-2 font-mono">{row.goods_key ?? "-"}</td><td className="border border-slate-200 px-3 py-2">{row.code ?? "-"}</td><td className="border border-slate-200 px-3 py-2">{row.msg ?? "-"}</td></tr>) : <tr><td className="border border-slate-200 px-3 py-2 text-slate-500" colSpan={5}>실패 항목이 없습니다.</td></tr>}</tbody></table></div>; }
function TitleKeywordSection({ rows }: { rows: ProductLaunchUploadRow[] }) { return <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-xl font-bold text-slate-950">Step 3. 상품명/키워드 준비</h2><p className="mt-3 text-sm text-slate-700">현재 MVP에서는 상품명/키워드를 6개 상품코드에 동일하게 적용하는 기준으로 준비합니다.</p><p className="mt-2 text-sm text-slate-700">향후 도매/소매 및 마켓별 SEO 전략 분기는 이 상품그룹 인식값을 기준으로 확장합니다.</p><GoodsKeyTable rows={rows} /><button type="button" disabled className="mt-5 rounded-lg border border-slate-300 bg-slate-100 px-4 py-2 text-sm font-semibold text-slate-500">상품명/키워드 단계 준비됨</button></section>; }
function FinalChecklist({ goodsKeyCount, priceDone }: { goodsKeyCount: number; priceDone: boolean }) { return <section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-xl font-bold text-slate-950">최종 체크리스트</h2><ul className="mt-4 space-y-2 text-sm text-slate-700"><li>상품업로드 결과 확인</li><li>goods_key 6개 확인: 현재 {goodsKeyCount}개</li><li>ptn_goods_cd prefix 그룹 인식 확인</li><li>가격설정 완료 확인: {priceDone ? "확인됨" : "결과 확인 필요"}</li><li>상품명/키워드 단계는 MVP 기준 동일 적용 예정</li><li>샵플링 마켓전송은 수동으로 진행</li></ul><p className="mt-4 rounded-lg bg-red-50 p-3 text-sm font-semibold text-red-700">마켓전송은 현재 OPS Center에서 자동 실행하지 않습니다. 샵플링 관리자에서 최종 확인 후 직접 전송하세요.</p></section>; }
function ResultRow({ label, value, mono }: { label: string; value: string | number; mono?: boolean }) { return <div className="grid gap-1 border-b border-slate-100 pb-3 md:grid-cols-[220px_1fr]"><dt className="font-semibold text-slate-700">{label}</dt><dd className={mono ? "font-mono text-slate-900" : "text-slate-900"}>{value}</dd></div>; }
function LinkRow({ label, href }: { label: string; href?: string }) { return <div className="grid gap-1 border-b border-slate-100 pb-3 md:grid-cols-[220px_1fr]"><dt className="font-semibold text-slate-700">{label}</dt><dd>{href ? <a className="text-blue-700 underline" href={href} target="_blank" rel="noreferrer">{href}</a> : "-"}</dd></div>; }
